site_name: MkDocs Basics
nav:
  - Getting Started: index.md
  - Customization: customization.md
repo_url: https://github.com/ethanchilds/Blog_MKdocs
theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
    - toc.integrate
  palette:
    - scheme: slate
      primary: purple
      accent: yellow
